### ISSUE TITLE
Araport has both a po and po-annotation loader

### ISSUE THREAD

**Issue by vivekkrish** [LegumeFederation/intermine-bio-sources-plant-ontology#1]
Hi @sammyjava -

Just an FYI, that the Araport project has created both a Plant Ontology (PO) and PO Annotation (via GAF2.0 file) loader.

Please see:
https://github.com/Arabidopsis-Information-Portal/intermine/tree/stable/bio/sources/po
https://github.com/Arabidopsis-Information-Portal/intermine/tree/stable/bio/sources/po-annotation

The PO loader is pretty straightforward (no real Java code needed). But if you plan on also loading PO annotation into your mines, I would recommend re-using our code.

Thank you!

**Comment by sammyjava** [comment]
Ah, thanks! Yeah, it's a trivial loader for PO. I'll be getting the PO annotation for QTLs, actually, for SoyMine from David Grant 
in the initial case, so that'll be a custom source that loads all sorts of stuff for QTLs, including TO annotation.

I'm trying to get all the QTLs organized with at least TO terms in the mines; Soybase already has the associations, which is 
convenient. I figured them out manually for BeanMine and CowpeaMine has only a few QTLs so far. So I figured I'd do the same for PO 
terms, which Soybase includes for QTLs.
